name: R Integration Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')"         
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Install additional packages (e.g., httr)
        run: |
          Rscript -e "install.packages('httr')"  # Install httr explicitly  
      
      - name: Install testthat
        run: Rscript -e "install.packages('testthat')"
      
      - name: List files for debugging
        run: |
          ls -R  # List all files to confirm the tests/testthat directory exists  
      
      - name: Run tests
        run: |
          Rscript -e "library(testthat)"
          Rscript -e "testthat::test_dir('tests/testthat/')"
